/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // here we create a manual sidebar for the User Guide so we can add multiple layers and create a category link for the main User Guide so it links in the breadcrumb and shows references to the documents under it as a starting point
  userGuideSidebar: [
    {
      type: 'category',
      label: 'User Guide',
      link: {
        type: 'generated-index',
        title: 'User Guide',
        description: 'If you are using or plan to use a Dataverse to host data but need some help learning how to load, manage and find data in the Dataverse, then this is the documentation for you.',
        slug: '/category/user-guide',
        keywords: ['user-guide'],
      },
      items: ['user-guide/account', 'user-guide/find-data', 'user-guide/dataverse-management', 'user-guide/dataset-management'],
    },
  ],

};

module.exports = sidebars;
